### PR TITLE
binco/i.should-get-to.work

### PR DESCRIPTION
**Pull request by binc0**

### CODE REVIEW

**Comment by binc0** [comment]
@LewisTehMinerz could you please have a look at pull errors. Thanks

**Comment by LewisTehMinerz** [comment]
sorry, only just saw this pull request.

seems like you're pointing these records to nowhere, any reason why?

**Comment by binc0** [comment]
Hello there, well I thought I was just testing, now I set up new records.

**Comment by LewisTehMinerz** [comment]
can you remove the comments from the files? the workflow can't read them with comments at the minute

**Comment by LewisTehMinerz** [comment]
your domains have been delegated 👍

**Comment by LewisTehMinerz** [comment]
heads up, you might need to add them to your hosting provider as aliases

**Comment by binc0** [comment]
Amazing, thanks 🙏 I'll fix it with my hosting provider.

**Pull request merged**
